# Generated by Django 2.1.3 on 2018-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='common', max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='common', max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(default='ex@ex.ex', max_length=254)),
            ],
        ),
    ]
